### ISSUE TITLE
Split out Annotations (and interface) into neutral Jar.

### ISSUE THREAD

**Issue by hsyed** [bennidi/mbassador#114]
Cleanly wrapping the project as a base component for a framework is quite hard to do without at minimum the annotations being separated. Please generate an API Jar In a simple neutral namespace ( like osgi, aop, javax).

I think that elements of the API that specify bits of functionality should also be included as separate interfaces parameterised only by the message type.

Off the top of my head behaviour for publishing and subscribing are candidates, but other elements like the model interface IMessagePublication and other similar interfaces should also be split out. 

I wouldn't mind doing this bit of work.

**Comment by bennidi** [comment]
I agree that modularity in terms of deployable artefacts could and should be improved. I was also thinking about this because of the work made by @dorkbox --> bennidi/eventbus-performance#1

It would be great to have a mechanism that allows to plugin extensions like a specific queue implementation that only works, for example with Java 8. Another idea would be the separation of the sync / async parts of message publications.

However, I did not understand your suggestion in detail. For example what would you put in the namespace neutral jar? The annotations only? What is your requirement for it? Are you aware that you can introduce your own annotations? Probably not flexible enough for your usecase but checkout #74 and `CustomHandlerAnnotationTest`.

I also did not understand what you mean by "elements of the API that specify bits of functionality should also be included as separate interfaces parameterised only by the message type." Can you explain?

Generally, if you want to contribute with making mbassador more modular you are more than welcome. Thank you!
