### ISSUE TITLE
Listeners loaded in different class loader are not called.

### ISSUE THREAD

**Issue by snimavat** [bennidi/mbassador#77]
We have a plugin based system, Mbassador works very well till the event bus and listeners are loaded by same class loader, however when listeners are in different class loader, even if they are subscribed, they will not get called.

Here's our scenario.
- Main application holds a singleton instance of event bus
- Main application creates a new class loader for each plugin and loads the plugin.
- Once the plugin is loaded, plugin manager gives newly loaded plugin, a chance to register its listeners and passes the event bus as parameter. Here plugin subscribes listeners.
- When main application receives a message, it will publish it using event bus. 
- Listeners in plugins (different class loader) will not get called.

Tried @Listener(references=References.Strong) too.

**Comment by chhh** [comment]
Maybe there should be an option in bus configuration to provide a class loader which should be used for class resolution? Or an option for "unsafe" mode, when classes will be matched just by their canonical names?

**Comment by fhntv24** [comment]
Actually, you could return same instance for event classes using classloader. Its a lot more safer way, but there is only one thing: event classes should *NOT* have static fields - this is due to securitty issues. (But i didn't test it actually, does same Class<?> share static fields or not).
You can simply do this by checking in plugin classloader if its event class then use reflection to return Class<?> from classloader. Because plugin classloader was created in main application, it will use main classloader. And thus it will return same instance of Class, and they will even share code ... And static variables .... So be carefull with this, but, IMHO, this is one of simplest way to do it.

I know, this is pretty old topic, but its still open and i was intested in it. And i know, sharing static variable is pretty bad - but i think it should be okay for messages... They are messages, and they shouldnt have static variables in them. But again, this is fix only for other side. As for MBassodor fix - IMHO, you shouldn't fix this. They are different classes. They are not the same. You cann't check if same class bytecode is used. *Actually, i wrote a few stupid lines and you shouldn't listen for me. It wont work with Oracle java, but can work for other implementations as it should throw exception because you cannot cast object if bytecode is diff., but this may cause security issues*
